
export enum GamePopupCode
{
    POPUP_NOT_MANAGED = 0,
    POPUP_MISSON = 1,
    POPUP_ADS,
    POPUP_NEW_CAT,
    POPUP_CUSTOMER_BOOK,
    POPUP_DAILY,
    POPUP_STORE,
    POPUP_SETTING,
    POPUP_TASK,
    POPUP_STORE_PURCHASE,
    POPUP_STORE_CONFIRM,
    POPUP_STORE_NOTIFICATION,
    
    POPUP_TIP,
    POPUP_BOOST
}
